services:
  - type: web
    name: audio-pattern-detection-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: UPLOAD_DIR
        value: uploads
      - key: RESULTS_DIR
        value: results
      - key: CORS_ORIGINS
        value: https://audio-pattern-detector.onrender.com
      - key: SUPABASE_URL
        fromDatabase:
          name: supabase-config
          property: url
      - key: SUPABASE_SERVICE_ROLE_KEY
        fromDatabase:
          name: supabase-config
          property: service_role_key
      - key: SUPABASE_BUCKET
        value: audio-analysis-files